<a href="https://colab.research.google.com/github/haifeng-jin/Colabs/blob/main/keras_issue_15909.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow as tf

In [ ]:
# tfk = tf.keras
# tfkl = tf.keras.layers
from tensorflow import keras

In [ ]:
tf.__version__, keras.__version__

('2.9.2', '2.9.0')

In [ ]:
input_shape = [28, 28, 1]

In [ ]:
def build_sub_model(input_shape):
    input_x = keras.layers.Input(shape=input_shape)
    h = keras.layers.Flatten()(input_x)
    h = keras.layers.Dense(10, activation='relu', activity_regularizer=tf.keras.regularizers.l1())(h)
    h = keras.layers.Dense(10, activation='relu')(h)

    return keras.models.Model(inputs=input_x, outputs=h)

keras.utils.set_random_seed(4)
# it is expected that this will show only 1 loss entry
sub_model = build_sub_model(input_shape)
sub_model(np.ones([10, 28, 28, 1]))
print(sub_model.losses)

[<tf.Tensor: shape=(), dtype=float32, numpy=0.08828449>]


In [ ]:
def build_model(input_shape):
    input_x = keras.layers.Input(shape=input_shape)
    sub_model = build_sub_model(input_shape)
    outputs = sub_model(input_x)
    return keras.models.Model(inputs=input_x, outputs=outputs)

keras.utils.set_random_seed(4)
# encapsulating test model inside another model
model = build_model(input_shape)

# should only show 1 loss but shows that
# regularization loss has been duplicated
model(np.ones([10, 28, 28, 1]))
print(model.losses)

model.compile(loss="mse")
import numpy as np
print(model.losses)

[<tf.Tensor: shape=(), dtype=float32, numpy=0.08828449>]
[<tf.Tensor: shape=(), dtype=float32, numpy=0.08828449>]
