<a href="https://colab.research.google.com/github/haifeng-jin/Colabs/blob/main/Torch_argsort_inconsistent_behavior_on_cpu_vs_gpu.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch
import numpy as np

print(torch.__version__)

# Numpy
values = np.array([1, 2, 3, 3, 2, 1])
print(np.argsort(values))

# Torch on cpu
a = torch.as_tensor(values)
print(torch.argsort(a, dim=0))

# Torch on cuda
a = torch.as_tensor(values, device="cuda:0")
print(torch.argsort(a, dim=0))

2.0.1+cu118
[0 5 1 4 2 3]
tensor([0, 5, 1, 4, 2, 3])
tensor([5, 0, 1, 4, 2, 3], device='cuda:0')
